parameters:
#    cabinate_restaurant.example.class: Cabinate\RestaurantBundle\Example

services:
#    cabinate_restaurant.example:
#        class: %cabinate_restaurant.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
