parameters:
#    cabinate_admin.example.class: Cabinate\AdminBundle\Example

services:
#    cabinate_admin.example:
#        class: %cabinate_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
