parameters:
#    cabinate_utils.example.class: Cabinate\UtilsBundle\Example

services:
#    cabinate_utils.example:
#        class: %cabinate_utils.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
