# tableunit
table_unit_get:
    pattern: /tableunits
    type: rest
    defaults: { _controller: CabinateAPIBundle:TableUnit:get }
    methods:  [GET]
table_unit_patch:
    pattern: /tableunits/{id}
    type: rest
    defaults: { _controller: CabinateAPIBundle:TableUnit:patch }
    methods:  [PATCH]
    requirements:
        id:   \d+
table_unit_post:
    pattern: /tableunits
    type: rest
    defaults: { _controller: CabinateAPIBundle:TableUnit:post }
    methods:  [POST]
# restaurant
restaurant_get:
    pattern: /restaurant
    type: rest
    defaults: { _controller: CabinateAPIBundle:Restaurant:get }
    methods:  [GET]
restaurant_patch:
    pattern: /restaurant/{id}
    type: rest
    defaults: { _controller: CabinateAPIBundle:Restaurant:patch }
    methods:  [PATCH]
    requirements:
        id:   \d+
restaurant_post:
    pattern: /restaurant
    type: rest
    defaults: { _controller: CabinateAPIBundle:Restaurant:post }
    methods:  [POST]
# order
order_get:
    pattern: /order
    type: rest
    defaults: { _controller: CabinateAPIBundle:Order:get }
    methods:  [GET]
order_put:
    pattern: /order/{id}
    type: rest
    defaults: { _controller: CabinateAPIBundle:Order:put }
    methods:  [PUT]
    requirements:
        id:   \d+
order_delete:
    pattern: /order/{id}
    type: rest
    defaults: { _controller: CabinateAPIBundle:Order:delete }
    methods:  [DELETE]
    requirements:
        id:   \d+
order_post:
    pattern: /order
    type: rest
    defaults: { _controller: CabinateAPIBundle:Order:post }
    methods:  [POST]
# product
product_get:
    pattern: /product
    type: rest
    defaults: { _controller: CabinateAPIBundle:Product:get }
    methods:  [GET]
product_put:
    pattern: /product/{id}
    type: rest
    defaults: { _controller: CabinateAPIBundle:Product:put }
    methods:  [PUT]
    requirements:
        id:   \d+
product_delete:
    pattern: /product/{id}
    type: rest
    defaults: { _controller: CabinateAPIBundle:Product:delete }
    methods:  [DELETE]
    requirements:
        id:   \d+
product_post:
    pattern: /product
    type: rest
    defaults: { _controller: CabinateAPIBundle:Product:post }
    methods:  [POST]
