# tableunit
table_unit_get:
    pattern: /tableunits
    type: rest
    defaults: { _controller: CabinateAPIBundle:TableUnit:get }
    methods:  [GET]
table_unit_patch:
    pattern: /tableunits/{id}
    type: rest
    defaults: { _controller: CabinateAPIBundle:TableUnit:patch }
    methods:  [PATCH]
    requirements:
        id:   \d+
table_unit_post:
    pattern: /tableunits
    type: rest
    defaults: { _controller: CabinateAPIBundle:TableUnit:post }
    methods:  [POST]
# restaurant
restaurant_get:
    pattern: /restaurant
    type: rest
    defaults: { _controller: CabinateAPIBundle:Restaurant:get }
    methods:  [GET]
restaurant_patch:
    pattern: /restaurant/{id}
    type: rest
    defaults: { _controller: CabinateAPIBundle:Restaurant:patch }
    methods:  [PATCH]
    requirements:
        id:   \d+
restaurant_post:
    pattern: /restaurant
    type: rest
    defaults: { _controller: CabinateAPIBundle:Restaurant:post }
    methods:  [POST]