# restaurant:
#     type: rest
#     resource: Cabinate\APIBundle\Controller\RestaurantController
# preoduct:
#     type: rest
#     resource: Cabinate\APIBundle\Controller\ProductController
table_unit_get:
    pattern: /tableunits
    type: rest
    defaults: { _controller: CabinateAPIBundle:TableUnit:get }
    methods:  [GET]
table_unit_patch:
    pattern: /tableunits
    type: rest
    defaults: { _controller: CabinateAPIBundle:TableUnit:patch }
    methods:  [PATCH]
# order:
#     type: rest
#     resource: Cabinate\APIBundle\Controller\OrderController
