parameters:
#    cabinate_dao.example.class: Cabinate\DAOBundle\Example

services:
#    cabinate_dao.example:
#        class: %cabinate_dao.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
